// 
// Decompiled by Procyon v0.6.0
// 

package com.google.android.gms.internal;

import com.google.android.gms.common.api.ResultCallback;
import java.util.concurrent.TimeUnit;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.Result;

public final class zzln<R extends Result> extends OptionalPendingResult<R>
{
    private final zzlc<R> zzacI;
    
    public zzln(final PendingResult<R> pendingResult) {
        if (!(pendingResult instanceof zzlc)) {
            throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
        }
        this.zzacI = (zzlc<R>)pendingResult;
    }
    
    @Override
    public R await() {
        return this.zzacI.await();
    }
    
    @Override
    public R await(final long n, final TimeUnit timeUnit) {
        return this.zzacI.await(n, timeUnit);
    }
    
    @Override
    public void cancel() {
        this.zzacI.cancel();
    }
    
    @Override
    public R get() {
        if (this.isDone()) {
            return this.await(0L, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }
    
    @Override
    public boolean isCanceled() {
        return this.zzacI.isCanceled();
    }
    
    @Override
    public boolean isDone() {
        return this.zzacI.isReady();
    }
    
    @Override
    public void setResultCallback(final ResultCallback<? super R> resultCallback) {
        this.zzacI.setResultCallback(resultCallback);
    }
    
    @Override
    public void setResultCallback(final ResultCallback<? super R> resultCallback, final long n, final TimeUnit timeUnit) {
        this.zzacI.setResultCallback(resultCallback, n, timeUnit);
    }
    
    @Override
    public void zza(final zza zza) {
        this.zzacI.zza(zza);
    }
    
    @Override
    public Integer zznF() {
        return this.zzacI.zznF();
    }
}
