// 
// Decompiled by Procyon v0.6.0
// 

package org.apache.commons.imaging.formats.tiff.constants;

import java.util.Collections;
import java.util.Arrays;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoGpsText;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoDouble;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoSLong;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoShortOrLong;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoDirectory;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoUndefined;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoSRational;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoAscii;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoShort;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoByte;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoRational;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoUnknown;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfoLong;
import org.apache.commons.imaging.formats.tiff.taginfos.TagInfo;
import java.util.List;

public final class ExifTagConstants
{
    public static final List<TagInfo> ALL_EXIF_TAGS;
    public static final int CONTRAST_1_VALUE_HIGH = 2;
    public static final int CONTRAST_1_VALUE_LOW = 1;
    public static final int CONTRAST_1_VALUE_NORMAL = 0;
    public static final int CUSTOM_RENDERED_VALUE_CUSTOM = 1;
    public static final int CUSTOM_RENDERED_VALUE_NORMAL = 0;
    public static final TagInfoLong EXIF_TAG_AFCP_IPTC;
    public static final TagInfoUnknown EXIF_TAG_ANNOTATIONS;
    public static final TagInfoRational EXIF_TAG_APERTURE_VALUE;
    public static final TagInfoByte EXIF_TAG_APPLICATION_NOTES;
    public static final TagInfoByte EXIF_TAG_BACKGROUND_COLOR_INDICATOR;
    public static final TagInfoByte EXIF_TAG_BACKGROUND_COLOR_VALUE;
    public static final TagInfoShort EXIF_TAG_BITS_PER_EXTENDED_RUN_LENGTH;
    public static final TagInfoShort EXIF_TAG_BITS_PER_RUN_LENGTH;
    public static final TagInfoAscii EXIF_TAG_BRIGHTNESS;
    public static final TagInfoSRational EXIF_TAG_BRIGHTNESS_VALUE;
    public static final TagInfoUndefined EXIF_TAG_CFAPATTERN;
    public static final TagInfoAscii EXIF_TAG_COLOR_CHARACTERIZATION;
    public static final TagInfoAscii EXIF_TAG_COLOR_SEQUENCE;
    public static final TagInfoByte EXIF_TAG_COLOR_TABLE;
    public static final TagInfoUndefined EXIF_TAG_COMPONENTS_CONFIGURATION;
    public static final TagInfoRational EXIF_TAG_COMPRESSED_BITS_PER_PIXEL;
    public static final TagInfoShort EXIF_TAG_CONTRAST_1;
    public static final TagInfoAscii EXIF_TAG_CONTRAST_2;
    public static final TagInfoAscii EXIF_TAG_CONVERTER;
    public static final TagInfoShort EXIF_TAG_CUSTOM_RENDERED;
    public static final TagInfoUnknown EXIF_TAG_DATA_TYPE;
    public static final TagInfoAscii EXIF_TAG_DATE_TIME_DIGITIZED;
    public static final TagInfoAscii EXIF_TAG_DATE_TIME_ORIGINAL;
    public static final TagInfoUndefined EXIF_TAG_DEVICE_SETTING_DESCRIPTION;
    public static final TagInfoRational EXIF_TAG_DIGITAL_ZOOM_RATIO;
    public static final TagInfoShort EXIF_TAG_EXIF_IMAGE_LENGTH;
    public static final TagInfoShort EXIF_TAG_EXIF_IMAGE_WIDTH;
    public static final TagInfoDirectory EXIF_TAG_EXIF_OFFSET;
    public static final TagInfoUndefined EXIF_TAG_EXIF_VERSION;
    public static final TagInfoAscii EXIF_TAG_EXPOSURE;
    public static final TagInfoSRational EXIF_TAG_EXPOSURE_COMPENSATION;
    public static final TagInfoRational EXIF_TAG_EXPOSURE_INDEX_EXIF_IFD;
    public static final TagInfoShort EXIF_TAG_EXPOSURE_MODE;
    public static final TagInfoShort EXIF_TAG_EXPOSURE_PROGRAM;
    public static final TagInfoRational EXIF_TAG_EXPOSURE_TIME;
    public static final TagInfoUndefined EXIF_TAG_FILE_SOURCE;
    public static final TagInfoShort EXIF_TAG_FLASH;
    public static final TagInfoUndefined EXIF_TAG_FLASHPIX_VERSION;
    public static final TagInfoRational EXIF_TAG_FLASH_ENERGY_EXIF_IFD;
    public static final TagInfoRational EXIF_TAG_FNUMBER;
    public static final TagInfoRational EXIF_TAG_FOCAL_LENGTH;
    public static final TagInfoShort EXIF_TAG_FOCAL_LENGTH_IN_35MM_FORMAT;
    public static final TagInfoShort EXIF_TAG_FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD;
    public static final TagInfoRational EXIF_TAG_FOCAL_PLANE_XRESOLUTION_EXIF_IFD;
    public static final TagInfoRational EXIF_TAG_FOCAL_PLANE_YRESOLUTION_EXIF_IFD;
    public static final TagInfoShort EXIF_TAG_GAIN_CONTROL;
    public static final TagInfoRational EXIF_TAG_GAMMA;
    public static final TagInfoDirectory EXIF_TAG_GPSINFO;
    public static final TagInfoShortOrLong EXIF_TAG_HCUSAGE;
    public static final TagInfoByte EXIF_TAG_IMAGE_COLOR_INDICATOR;
    public static final TagInfoByte EXIF_TAG_IMAGE_COLOR_VALUE;
    public static final TagInfoUnknown EXIF_TAG_IMAGE_DEPTH;
    public static final TagInfoUnknown EXIF_TAG_IMAGE_HISTORY;
    public static final TagInfoUnknown EXIF_TAG_IMAGE_NUMBER;
    public static final TagInfoAscii EXIF_TAG_IMAGE_UNIQUE_ID;
    public static final TagInfoLong EXIF_TAG_INTERGRAPH_FLAG_REGISTERS;
    public static final TagInfoShort EXIF_TAG_INTERGRAPH_PACKET_DATA;
    public static final TagInfoAscii EXIF_TAG_INTEROPERABILITY_INDEX;
    public static final TagInfoUndefined EXIF_TAG_INTEROPERABILITY_VERSION;
    public static final TagInfoDirectory EXIF_TAG_INTEROP_OFFSET;
    public static final TagInfoLong EXIF_TAG_IPTC_NAA;
    public static final TagInfoShort EXIF_TAG_ISO;
    public static final TagInfoAscii EXIF_TAG_IT8HEADER;
    public static final TagInfoLong EXIF_TAG_JPG_FROM_RAW_LENGTH_IFD2;
    public static final TagInfoLong EXIF_TAG_JPG_FROM_RAW_LENGTH_SUB_IFD;
    public static final TagInfoLong EXIF_TAG_JPG_FROM_RAW_LENGTH_SUB_IFD2;
    public static final TagInfoLong EXIF_TAG_JPG_FROM_RAW_START_IFD2;
    public static final TagInfoLong EXIF_TAG_JPG_FROM_RAW_START_SUB_IFD;
    public static final TagInfoLong EXIF_TAG_JPG_FROM_RAW_START_SUB_IFD2;
    public static final TagInfoLong EXIF_TAG_LEAF_DATA;
    public static final TagInfoLong EXIF_TAG_LEAF_SUB_IFD;
    public static final TagInfoAscii EXIF_TAG_LENS;
    public static final TagInfoShort EXIF_TAG_LIGHT_SOURCE;
    public static final TagInfoUndefined EXIF_TAG_MAKER_NOTE;
    public static final TagInfoUnknown EXIF_TAG_MATTEING;
    public static final TagInfoRational EXIF_TAG_MAX_APERTURE_VALUE;
    public static final TagInfoShort EXIF_TAG_METERING_MODE;
    public static final TagInfoUnknown EXIF_TAG_MODEL_2;
    public static final TagInfoAscii EXIF_TAG_MOIRE_FILTER;
    public static final TagInfoUnknown EXIF_TAG_NOISE_2;
    public static final TagInfoSLong EXIF_TAG_OFFSET_SCHEMA;
    public static final TagInfoUndefined EXIF_TAG_OPTO_ELECTRIC_CONV_FACTOR;
    public static final TagInfoLong EXIF_TAG_OTHER_IMAGE_LENGTH;
    public static final TagInfoLong EXIF_TAG_OTHER_IMAGE_START;
    public static final TagInfoAscii EXIF_TAG_OWNER_NAME;
    public static final TagInfoByte EXIF_TAG_PHOTOSHOP_SETTINGS;
    public static final TagInfoByte EXIF_TAG_PIXEL_INTENSITY_RANGE;
    public static final TagInfoLong EXIF_TAG_PREVIEW_IMAGE_LENGTH_IFD0;
    public static final TagInfoLong EXIF_TAG_PREVIEW_IMAGE_LENGTH_MAKER_NOTES;
    public static final TagInfoLong EXIF_TAG_PREVIEW_IMAGE_LENGTH_SUB_IFD1;
    public static final TagInfoLong EXIF_TAG_PREVIEW_IMAGE_START_IFD0;
    public static final TagInfoLong EXIF_TAG_PREVIEW_IMAGE_START_MAKER_NOTES;
    public static final TagInfoLong EXIF_TAG_PREVIEW_IMAGE_START_SUB_IFD1;
    public static final TagInfoUndefined EXIF_TAG_PRINT_IM;
    public static final TagInfoAscii EXIF_TAG_PROCESSING_SOFTWARE;
    public static final TagInfoShort EXIF_TAG_RASTER_PADDING;
    public static final TagInfoAscii EXIF_TAG_RAW_FILE;
    public static final TagInfoAscii EXIF_TAG_RELATED_SOUND_FILE;
    public static final TagInfoShort EXIF_TAG_SATURATION_1;
    public static final TagInfoAscii EXIF_TAG_SATURATION_2;
    public static final TagInfoShort EXIF_TAG_SCENE_CAPTURE_TYPE;
    public static final TagInfoUndefined EXIF_TAG_SCENE_TYPE;
    public static final TagInfoUnknown EXIF_TAG_SECURITY_CLASSIFICATION;
    public static final TagInfoAscii EXIF_TAG_SEMINFO;
    public static final TagInfoShort EXIF_TAG_SENSING_METHOD_EXIF_IFD;
    public static final TagInfoAscii EXIF_TAG_SERIAL_NUMBER;
    public static final TagInfoAscii EXIF_TAG_SHADOWS;
    public static final TagInfoShort EXIF_TAG_SHARPNESS_1;
    public static final TagInfoAscii EXIF_TAG_SHARPNESS_2;
    public static final TagInfoSRational EXIF_TAG_SHUTTER_SPEED_VALUE;
    public static final TagInfoAscii EXIF_TAG_SITE;
    public static final TagInfoAscii EXIF_TAG_SMOOTHNESS;
    public static final TagInfoAscii EXIF_TAG_SOFTWARE;
    public static final TagInfoUndefined EXIF_TAG_SPATIAL_FREQUENCY_RESPONSE_2;
    public static final TagInfoAscii EXIF_TAG_SPECTRAL_SENSITIVITY;
    public static final TagInfoDouble EXIF_TAG_STO_NITS;
    public static final TagInfoShort EXIF_TAG_SUBJECT_AREA;
    public static final TagInfoRational EXIF_TAG_SUBJECT_DISTANCE;
    public static final TagInfoShort EXIF_TAG_SUBJECT_DISTANCE_RANGE;
    public static final TagInfoShort EXIF_TAG_SUBJECT_LOCATION;
    public static final TagInfoAscii EXIF_TAG_SUB_SEC_TIME;
    public static final TagInfoAscii EXIF_TAG_SUB_SEC_TIME_DIGITIZED;
    public static final TagInfoAscii EXIF_TAG_SUB_SEC_TIME_ORIGINAL;
    public static final TagInfoUnknown EXIF_TAG_TIFF_EPSTANDARD_ID_2;
    public static final TagInfoUnknown EXIF_TAG_TILE_DEPTH;
    public static final TagInfoByte EXIF_TAG_TRANSPARENCY_INDICATOR;
    public static final TagInfoGpsText EXIF_TAG_USER_COMMENT;
    public static final TagInfoShort EXIF_TAG_WHITE_BALANCE_1;
    public static final TagInfoAscii EXIF_TAG_WHITE_BALANCE_2;
    public static final int EXPOSURE_MODE_VALUE_AUTO = 0;
    public static final int EXPOSURE_MODE_VALUE_AUTO_BRACKET = 2;
    public static final int EXPOSURE_MODE_VALUE_MANUAL = 1;
    public static final int EXPOSURE_PROGRAM_VALUE_ACTION_HIGH_SPEED = 6;
    public static final int EXPOSURE_PROGRAM_VALUE_APERTURE_PRIORITY_AE = 3;
    public static final int EXPOSURE_PROGRAM_VALUE_CREATIVE_SLOW_SPEED = 5;
    public static final int EXPOSURE_PROGRAM_VALUE_LANDSCAPE = 8;
    public static final int EXPOSURE_PROGRAM_VALUE_MANUAL = 1;
    public static final int EXPOSURE_PROGRAM_VALUE_PORTRAIT = 7;
    public static final int EXPOSURE_PROGRAM_VALUE_PROGRAM_AE = 2;
    public static final int EXPOSURE_PROGRAM_VALUE_SHUTTER_SPEED_PRIORITY_AE = 4;
    public static final int FILE_SOURCE_VALUE_DIGITAL_CAMERA = 3;
    public static final int FILE_SOURCE_VALUE_FILM_SCANNER = 1;
    public static final int FILE_SOURCE_VALUE_REFLECTION_PRINT_SCANNER = 2;
    public static final int FLASH_VALUE_AUTO_DID_NOT_FIRE = 24;
    public static final int FLASH_VALUE_AUTO_DID_NOT_FIRE_RED_EYE_REDUCTION = 88;
    public static final int FLASH_VALUE_AUTO_FIRED = 25;
    public static final int FLASH_VALUE_AUTO_FIRED_RED_EYE_REDUCTION = 89;
    public static final int FLASH_VALUE_AUTO_FIRED_RED_EYE_REDUCTION_RETURN_DETECTED = 95;
    public static final int FLASH_VALUE_AUTO_FIRED_RED_EYE_REDUCTION_RETURN_NOT_DETECTED = 93;
    public static final int FLASH_VALUE_AUTO_FIRED_RETURN_DETECTED = 31;
    public static final int FLASH_VALUE_AUTO_FIRED_RETURN_NOT_DETECTED = 29;
    public static final int FLASH_VALUE_FIRED = 1;
    public static final int FLASH_VALUE_FIRED_RED_EYE_REDUCTION = 65;
    public static final int FLASH_VALUE_FIRED_RED_EYE_REDUCTION_RETURN_DETECTED = 71;
    public static final int FLASH_VALUE_FIRED_RED_EYE_REDUCTION_RETURN_NOT_DETECTED = 69;
    public static final int FLASH_VALUE_FIRED_RETURN_DETECTED = 7;
    public static final int FLASH_VALUE_FIRED_RETURN_NOT_DETECTED = 5;
    public static final int FLASH_VALUE_NO_FLASH = 0;
    public static final int FLASH_VALUE_NO_FLASH_FUNCTION = 32;
    public static final int FLASH_VALUE_OFF = 16;
    public static final int FLASH_VALUE_OFF_DID_NOT_FIRE_RETURN_NOT_DETECTED = 20;
    public static final int FLASH_VALUE_OFF_NO_FLASH_FUNCTION = 48;
    public static final int FLASH_VALUE_OFF_RED_EYE_REDUCTION = 80;
    public static final int FLASH_VALUE_ON = 9;
    public static final int FLASH_VALUE_ON_DID_NOT_FIRE = 8;
    public static final int FLASH_VALUE_ON_RED_EYE_REDUCTION = 73;
    public static final int FLASH_VALUE_ON_RED_EYE_REDUCTION_RETURN_DETECTED = 79;
    public static final int FLASH_VALUE_ON_RED_EYE_REDUCTION_RETURN_NOT_DETECTED = 77;
    public static final int FLASH_VALUE_ON_RETURN_DETECTED = 15;
    public static final int FLASH_VALUE_ON_RETURN_NOT_DETECTED = 13;
    public static final int FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD_VALUE_CM = 3;
    public static final int FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD_VALUE_INCHES = 2;
    public static final int FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD_VALUE_MM = 4;
    public static final int FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD_VALUE_NONE = 1;
    public static final int FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD_VALUE_UM = 5;
    public static final int GAIN_CONTROL_VALUE_HIGH_GAIN_DOWN = 4;
    public static final int GAIN_CONTROL_VALUE_HIGH_GAIN_UP = 2;
    public static final int GAIN_CONTROL_VALUE_LOW_GAIN_DOWN = 3;
    public static final int GAIN_CONTROL_VALUE_LOW_GAIN_UP = 1;
    public static final int GAIN_CONTROL_VALUE_NONE = 0;
    public static final int LIGHT_SOURCE_VALUE_CLOUDY = 10;
    public static final int LIGHT_SOURCE_VALUE_COOL_WHITE_FLUORESCENT = 14;
    public static final int LIGHT_SOURCE_VALUE_D50 = 23;
    public static final int LIGHT_SOURCE_VALUE_D55 = 20;
    public static final int LIGHT_SOURCE_VALUE_D65 = 21;
    public static final int LIGHT_SOURCE_VALUE_D75 = 22;
    public static final int LIGHT_SOURCE_VALUE_DAYLIGHT = 1;
    public static final int LIGHT_SOURCE_VALUE_DAYLIGHT_FLUORESCENT = 12;
    public static final int LIGHT_SOURCE_VALUE_DAY_WHITE_FLUORESCENT = 13;
    public static final int LIGHT_SOURCE_VALUE_FINE_WEATHER = 9;
    public static final int LIGHT_SOURCE_VALUE_FLASH = 4;
    public static final int LIGHT_SOURCE_VALUE_FLUORESCENT = 2;
    public static final int LIGHT_SOURCE_VALUE_ISO_STUDIO_TUNGSTEN = 24;
    public static final int LIGHT_SOURCE_VALUE_OTHER = 255;
    public static final int LIGHT_SOURCE_VALUE_SHADE = 11;
    public static final int LIGHT_SOURCE_VALUE_STANDARD_LIGHT_A = 17;
    public static final int LIGHT_SOURCE_VALUE_STANDARD_LIGHT_B = 18;
    public static final int LIGHT_SOURCE_VALUE_STANDARD_LIGHT_C = 19;
    public static final int LIGHT_SOURCE_VALUE_TUNGSTEN = 3;
    public static final int LIGHT_SOURCE_VALUE_WHITE_FLUORESCENT = 15;
    public static final int METERING_MODE_VALUE_AVERAGE = 1;
    public static final int METERING_MODE_VALUE_CENTER_WEIGHTED_AVERAGE = 2;
    public static final int METERING_MODE_VALUE_MULTI_SEGMENT = 5;
    public static final int METERING_MODE_VALUE_MULTI_SPOT = 4;
    public static final int METERING_MODE_VALUE_OTHER = 255;
    public static final int METERING_MODE_VALUE_PARTIAL = 6;
    public static final int METERING_MODE_VALUE_SPOT = 3;
    public static final int SATURATION_1_VALUE_HIGH = 2;
    public static final int SATURATION_1_VALUE_LOW = 1;
    public static final int SATURATION_1_VALUE_NORMAL = 0;
    public static final int SCENE_CAPTURE_TYPE_VALUE_LANDSCAPE = 1;
    public static final int SCENE_CAPTURE_TYPE_VALUE_NIGHT = 3;
    public static final int SCENE_CAPTURE_TYPE_VALUE_PORTRAIT = 2;
    public static final int SCENE_CAPTURE_TYPE_VALUE_STANDARD = 0;
    public static final int SENSING_METHOD_EXIF_IFD_VALUE_COLOR_SEQUENTIAL_AREA = 5;
    public static final int SENSING_METHOD_EXIF_IFD_VALUE_COLOR_SEQUENTIAL_LINEAR = 8;
    public static final int SENSING_METHOD_EXIF_IFD_VALUE_NOT_DEFINED = 1;
    public static final int SENSING_METHOD_EXIF_IFD_VALUE_ONE_CHIP_COLOR_AREA = 2;
    public static final int SENSING_METHOD_EXIF_IFD_VALUE_THREE_CHIP_COLOR_AREA = 4;
    public static final int SENSING_METHOD_EXIF_IFD_VALUE_TRILINEAR = 7;
    public static final int SENSING_METHOD_EXIF_IFD_VALUE_TWO_CHIP_COLOR_AREA = 3;
    public static final int SHARPNESS_1_VALUE_HARD = 2;
    public static final int SHARPNESS_1_VALUE_NORMAL = 0;
    public static final int SHARPNESS_1_VALUE_SOFT = 1;
    public static final int SUBJECT_DISTANCE_RANGE_VALUE_CLOSE = 2;
    public static final int SUBJECT_DISTANCE_RANGE_VALUE_DISTANT = 3;
    public static final int SUBJECT_DISTANCE_RANGE_VALUE_MACRO = 1;
    public static final int WHITE_BALANCE_1_VALUE_AUTO = 0;
    public static final int WHITE_BALANCE_1_VALUE_MANUAL = 1;
    
    static {
        EXIF_TAG_INTEROPERABILITY_INDEX = new TagInfoAscii("InteroperabilityIndex", 1, -1, TiffDirectoryType.EXIF_DIRECTORY_INTEROP_IFD);
        EXIF_TAG_INTEROPERABILITY_VERSION = new TagInfoUndefined("InteroperabilityVersion", 2, 1, TiffDirectoryType.EXIF_DIRECTORY_INTEROP_IFD);
        EXIF_TAG_PROCESSING_SOFTWARE = new TagInfoAscii("ProcessingSoftware", 11, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_SOFTWARE = new TagInfoAscii("Software", 305, -1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_PREVIEW_IMAGE_START_IFD0 = new TagInfoLong("PreviewImageStart", 273, 1, TiffDirectoryType.EXIF_DIRECTORY_IFD0, true);
        EXIF_TAG_PREVIEW_IMAGE_START_SUB_IFD1 = new TagInfoLong("PreviewImageStart", 273, 1, TiffDirectoryType.EXIF_DIRECTORY_SUB_IFD1, true);
        EXIF_TAG_JPG_FROM_RAW_START_SUB_IFD2 = new TagInfoLong("JpgFromRawStart", 273, 1, TiffDirectoryType.EXIF_DIRECTORY_SUB_IFD2, true);
        EXIF_TAG_PREVIEW_IMAGE_LENGTH_IFD0 = new TagInfoLong("PreviewImageLength", 279, 1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_PREVIEW_IMAGE_LENGTH_SUB_IFD1 = new TagInfoLong("PreviewImageLength", 279, 1, TiffDirectoryType.EXIF_DIRECTORY_SUB_IFD1);
        EXIF_TAG_JPG_FROM_RAW_LENGTH_SUB_IFD2 = new TagInfoLong("JpgFromRawLength", 279, 1, TiffDirectoryType.EXIF_DIRECTORY_SUB_IFD2);
        EXIF_TAG_PREVIEW_IMAGE_START_MAKER_NOTES = new TagInfoLong("PreviewImageStart", 513, 1, TiffDirectoryType.EXIF_DIRECTORY_MAKER_NOTES);
        EXIF_TAG_JPG_FROM_RAW_START_SUB_IFD = new TagInfoLong("JpgFromRawStart", 513, 1, TiffDirectoryType.EXIF_DIRECTORY_SUB_IFD, true);
        EXIF_TAG_JPG_FROM_RAW_START_IFD2 = new TagInfoLong("JpgFromRawStart", 513, 1, TiffDirectoryType.EXIF_DIRECTORY_IFD2, true);
        EXIF_TAG_OTHER_IMAGE_START = new TagInfoLong("OtherImageStart", 513, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN, true);
        EXIF_TAG_PREVIEW_IMAGE_LENGTH_MAKER_NOTES = new TagInfoLong("PreviewImageLength", 514, 1, TiffDirectoryType.EXIF_DIRECTORY_MAKER_NOTES);
        EXIF_TAG_JPG_FROM_RAW_LENGTH_SUB_IFD = new TagInfoLong("JpgFromRawLength", 514, 1, TiffDirectoryType.EXIF_DIRECTORY_SUB_IFD);
        EXIF_TAG_JPG_FROM_RAW_LENGTH_IFD2 = new TagInfoLong("JpgFromRawLength", 514, 1, TiffDirectoryType.EXIF_DIRECTORY_IFD2);
        EXIF_TAG_OTHER_IMAGE_LENGTH = new TagInfoLong("OtherImageLength", 514, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_APPLICATION_NOTES = new TagInfoByte("ApplicationNotes", 700, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MATTEING = new TagInfoUnknown("Matteing", 32995, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_DATA_TYPE = new TagInfoUnknown("DataType", 32996, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_DEPTH = new TagInfoUnknown("ImageDepth", 32997, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_TILE_DEPTH = new TagInfoUnknown("TileDepth", 32998, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MODEL_2 = new TagInfoUnknown("Model2", 33405, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_EXPOSURE_TIME = new TagInfoRational("ExposureTime", 33434, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FNUMBER = new TagInfoRational("FNumber", 33437, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_IPTC_NAA = new TagInfoLong("IPTC-NAA", 33723, 1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_INTERGRAPH_PACKET_DATA = new TagInfoShort("IntergraphPacketData", 33918, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_INTERGRAPH_FLAG_REGISTERS = new TagInfoLong("IntergraphFlagRegisters", 33919, 16, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SITE = new TagInfoAscii("Site", 34016, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_COLOR_SEQUENCE = new TagInfoAscii("ColorSequence", 34017, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IT8HEADER = new TagInfoAscii("IT8Header", 34018, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_RASTER_PADDING = new TagInfoShort("RasterPadding", 34019, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BITS_PER_RUN_LENGTH = new TagInfoShort("BitsPerRunLength", 34020, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BITS_PER_EXTENDED_RUN_LENGTH = new TagInfoShort("BitsPerExtendedRunLength", 34021, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_COLOR_TABLE = new TagInfoByte("ColorTable", 34022, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_COLOR_INDICATOR = new TagInfoByte("ImageColorIndicator", 34023, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BACKGROUND_COLOR_INDICATOR = new TagInfoByte("BackgroundColorIndicator", 34024, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_COLOR_VALUE = new TagInfoByte("ImageColorValue", 34025, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_BACKGROUND_COLOR_VALUE = new TagInfoByte("BackgroundColorValue", 34026, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PIXEL_INTENSITY_RANGE = new TagInfoByte("PixelIntensityRange", 34027, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_TRANSPARENCY_INDICATOR = new TagInfoByte("TransparencyIndicator", 34028, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_COLOR_CHARACTERIZATION = new TagInfoAscii("ColorCharacterization", 34029, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_HCUSAGE = new TagInfoShortOrLong("HCUsage", 34030, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SEMINFO = new TagInfoAscii("SEMInfo", 34118, 1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_AFCP_IPTC = new TagInfoLong("AFCP_IPTC", 34152, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_LEAF_DATA = new TagInfoLong("LeafData", 34310, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PHOTOSHOP_SETTINGS = new TagInfoByte("PhotoshopSettings", 34377, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_EXIF_OFFSET = new TagInfoDirectory("ExifOffset", 34665, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_EXPOSURE_PROGRAM = new TagInfoShort("ExposureProgram", 34850, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SPECTRAL_SENSITIVITY = new TagInfoAscii("SpectralSensitivity", 34852, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_GPSINFO = new TagInfoDirectory("GPSInfo", 34853, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_ISO = new TagInfoShort("PhotographicSensitivity", 34855, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_OPTO_ELECTRIC_CONV_FACTOR = new TagInfoUndefined("Opto - Electric Conv Factor", 34856, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_LEAF_SUB_IFD = new TagInfoLong("LeafSubIFD", 34954, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_EXIF_VERSION = new TagInfoUndefined("ExifVersion", 36864, 4, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_DATE_TIME_ORIGINAL = new TagInfoAscii("DateTimeOriginal", 36867, 20, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_DATE_TIME_DIGITIZED = new TagInfoAscii("DateTimeDigitized", 36868, 20, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_COMPONENTS_CONFIGURATION = new TagInfoUndefined("ComponentsConfiguration", 37121, 4, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_COMPRESSED_BITS_PER_PIXEL = new TagInfoRational("CompressedBitsPerPixel", 37122, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SHUTTER_SPEED_VALUE = new TagInfoSRational("ShutterSpeedValue", 37377, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_APERTURE_VALUE = new TagInfoRational("ApertureValue", 37378, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_BRIGHTNESS_VALUE = new TagInfoSRational("BrightnessValue", 37379, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXPOSURE_COMPENSATION = new TagInfoSRational("ExposureCompensation", 37380, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_MAX_APERTURE_VALUE = new TagInfoRational("MaxApertureValue", 37381, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUBJECT_DISTANCE = new TagInfoRational("Subject Distance", 37382, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_METERING_MODE = new TagInfoShort("MeteringMode", 37383, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_LIGHT_SOURCE = new TagInfoShort("LightSource", 37384, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FLASH = new TagInfoShort("Flash", 37385, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FOCAL_LENGTH = new TagInfoRational("FocalLength", 37386, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUBJECT_AREA = new TagInfoShort("SubjectArea", 37396, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_STO_NITS = new TagInfoDouble("StoNits", 37439, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_MAKER_NOTE = new TagInfoUndefined("MakerNote", 37500, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_USER_COMMENT = new TagInfoGpsText("UserComment", 37510, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUB_SEC_TIME = new TagInfoAscii("SubSecTime", 37520, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUB_SEC_TIME_ORIGINAL = new TagInfoAscii("SubSecTimeOriginal", 37521, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SUB_SEC_TIME_DIGITIZED = new TagInfoAscii("SubSecTimeDigitized", 37522, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FLASHPIX_VERSION = new TagInfoUndefined("FlashpixVersion", 40960, 4, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXIF_IMAGE_WIDTH = new TagInfoShort("ExifImageWidth", 40962, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXIF_IMAGE_LENGTH = new TagInfoShort("ExifImageLength", 40963, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_RELATED_SOUND_FILE = new TagInfoAscii("RelatedSoundFile", 40964, 13, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_INTEROP_OFFSET = new TagInfoDirectory("InteropOffset", 40965, 1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_FLASH_ENERGY_EXIF_IFD = new TagInfoRational("FlashEnergy", 41483, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SPATIAL_FREQUENCY_RESPONSE_2 = new TagInfoUndefined("SpatialFrequencyResponse", 41484, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_NOISE_2 = new TagInfoUnknown("Noise", 41485, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_FOCAL_PLANE_XRESOLUTION_EXIF_IFD = new TagInfoRational("FocalPlaneXResolution", 41486, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FOCAL_PLANE_YRESOLUTION_EXIF_IFD = new TagInfoRational("FocalPlaneYResolution", 41487, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD = new TagInfoShort("FocalPlaneResolutionUnit", 41488, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_IMAGE_NUMBER = new TagInfoUnknown("ImageNumber", 41489, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SECURITY_CLASSIFICATION = new TagInfoUnknown("SecurityClassification", 41490, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_IMAGE_HISTORY = new TagInfoUnknown("ImageHistory", 41491, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SUBJECT_LOCATION = new TagInfoShort("SubjectLocation", 41492, 2, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXPOSURE_INDEX_EXIF_IFD = new TagInfoRational("ExposureIndex", 41493, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_TIFF_EPSTANDARD_ID_2 = new TagInfoUnknown("TIFF-EPStandardID", 41494, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SENSING_METHOD_EXIF_IFD = new TagInfoShort("SensingMethod", 41495, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FILE_SOURCE = new TagInfoUndefined("FileSource", 41728, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SCENE_TYPE = new TagInfoUndefined("SceneType", 41729, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_CFAPATTERN = new TagInfoUndefined("CFAPattern", 41730, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_CUSTOM_RENDERED = new TagInfoShort("CustomRendered", 41985, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXPOSURE_MODE = new TagInfoShort("ExposureMode", 41986, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_WHITE_BALANCE_1 = new TagInfoShort("WhiteBalance", 41987, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_DIGITAL_ZOOM_RATIO = new TagInfoRational("DigitalZoomRatio", 41988, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_FOCAL_LENGTH_IN_35MM_FORMAT = new TagInfoShort("FocalLengthIn35mmFormat", 41989, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SCENE_CAPTURE_TYPE = new TagInfoShort("SceneCaptureType", 41990, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_GAIN_CONTROL = new TagInfoShort("GainControl", 41991, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_CONTRAST_1 = new TagInfoShort("Contrast", 41992, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SATURATION_1 = new TagInfoShort("Saturation", 41993, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SHARPNESS_1 = new TagInfoShort("Sharpness", 41994, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_DEVICE_SETTING_DESCRIPTION = new TagInfoUndefined("DeviceSettingDescription", 41995, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_SUBJECT_DISTANCE_RANGE = new TagInfoShort("SubjectDistanceRange", 41996, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_IMAGE_UNIQUE_ID = new TagInfoAscii("ImageUniqueID", 42016, 33, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_GAMMA = new TagInfoRational("Gamma", 42240, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_ANNOTATIONS = new TagInfoUnknown("Annotations", 50255, -1, TiffDirectoryType.EXIF_DIRECTORY_UNKNOWN);
        EXIF_TAG_PRINT_IM = new TagInfoUndefined("PrintIM", 50341, 1, TiffDirectoryType.EXIF_DIRECTORY_IFD0);
        EXIF_TAG_OFFSET_SCHEMA = new TagInfoSLong("OffsetSchema", 59933, 1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_OWNER_NAME = new TagInfoAscii("OwnerName", 65000, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SERIAL_NUMBER = new TagInfoAscii("SerialNumber", 65001, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_LENS = new TagInfoAscii("Lens", 65002, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_RAW_FILE = new TagInfoAscii("RawFile", 65100, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_CONVERTER = new TagInfoAscii("Converter", 65101, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_WHITE_BALANCE_2 = new TagInfoAscii("WhiteBalance", 65102, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_EXPOSURE = new TagInfoAscii("Exposure", 65105, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SHADOWS = new TagInfoAscii("Shadows", 65106, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_BRIGHTNESS = new TagInfoAscii("Brightness", 65107, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_CONTRAST_2 = new TagInfoAscii("Contrast", 65108, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SATURATION_2 = new TagInfoAscii("Saturation", 65109, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SHARPNESS_2 = new TagInfoAscii("Sharpness", 65110, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_SMOOTHNESS = new TagInfoAscii("Smoothness", 65111, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        EXIF_TAG_MOIRE_FILTER = new TagInfoAscii("MoireFilter", 65112, -1, TiffDirectoryType.EXIF_DIRECTORY_EXIF_IFD);
        ALL_EXIF_TAGS = Collections.unmodifiableList((List<? extends TagInfo>)Arrays.asList(ExifTagConstants.EXIF_TAG_INTEROPERABILITY_INDEX, ExifTagConstants.EXIF_TAG_INTEROPERABILITY_VERSION, ExifTagConstants.EXIF_TAG_PROCESSING_SOFTWARE, ExifTagConstants.EXIF_TAG_SOFTWARE, ExifTagConstants.EXIF_TAG_PREVIEW_IMAGE_START_IFD0, ExifTagConstants.EXIF_TAG_PREVIEW_IMAGE_START_SUB_IFD1, ExifTagConstants.EXIF_TAG_JPG_FROM_RAW_START_SUB_IFD2, ExifTagConstants.EXIF_TAG_PREVIEW_IMAGE_LENGTH_IFD0, ExifTagConstants.EXIF_TAG_PREVIEW_IMAGE_LENGTH_SUB_IFD1, ExifTagConstants.EXIF_TAG_JPG_FROM_RAW_LENGTH_SUB_IFD2, ExifTagConstants.EXIF_TAG_PREVIEW_IMAGE_START_MAKER_NOTES, ExifTagConstants.EXIF_TAG_JPG_FROM_RAW_START_SUB_IFD, ExifTagConstants.EXIF_TAG_JPG_FROM_RAW_START_IFD2, ExifTagConstants.EXIF_TAG_OTHER_IMAGE_START, ExifTagConstants.EXIF_TAG_PREVIEW_IMAGE_LENGTH_MAKER_NOTES, ExifTagConstants.EXIF_TAG_JPG_FROM_RAW_LENGTH_SUB_IFD, ExifTagConstants.EXIF_TAG_JPG_FROM_RAW_LENGTH_IFD2, ExifTagConstants.EXIF_TAG_OTHER_IMAGE_LENGTH, ExifTagConstants.EXIF_TAG_APPLICATION_NOTES, ExifTagConstants.EXIF_TAG_MATTEING, ExifTagConstants.EXIF_TAG_DATA_TYPE, ExifTagConstants.EXIF_TAG_IMAGE_DEPTH, ExifTagConstants.EXIF_TAG_TILE_DEPTH, ExifTagConstants.EXIF_TAG_MODEL_2, ExifTagConstants.EXIF_TAG_EXPOSURE_TIME, ExifTagConstants.EXIF_TAG_FNUMBER, ExifTagConstants.EXIF_TAG_IPTC_NAA, ExifTagConstants.EXIF_TAG_INTERGRAPH_PACKET_DATA, ExifTagConstants.EXIF_TAG_INTERGRAPH_FLAG_REGISTERS, ExifTagConstants.EXIF_TAG_SITE, ExifTagConstants.EXIF_TAG_COLOR_SEQUENCE, ExifTagConstants.EXIF_TAG_IT8HEADER, ExifTagConstants.EXIF_TAG_RASTER_PADDING, ExifTagConstants.EXIF_TAG_BITS_PER_RUN_LENGTH, ExifTagConstants.EXIF_TAG_BITS_PER_EXTENDED_RUN_LENGTH, ExifTagConstants.EXIF_TAG_COLOR_TABLE, ExifTagConstants.EXIF_TAG_IMAGE_COLOR_INDICATOR, ExifTagConstants.EXIF_TAG_BACKGROUND_COLOR_INDICATOR, ExifTagConstants.EXIF_TAG_IMAGE_COLOR_VALUE, ExifTagConstants.EXIF_TAG_BACKGROUND_COLOR_VALUE, ExifTagConstants.EXIF_TAG_PIXEL_INTENSITY_RANGE, ExifTagConstants.EXIF_TAG_TRANSPARENCY_INDICATOR, ExifTagConstants.EXIF_TAG_COLOR_CHARACTERIZATION, ExifTagConstants.EXIF_TAG_HCUSAGE, ExifTagConstants.EXIF_TAG_SEMINFO, ExifTagConstants.EXIF_TAG_AFCP_IPTC, ExifTagConstants.EXIF_TAG_LEAF_DATA, ExifTagConstants.EXIF_TAG_PHOTOSHOP_SETTINGS, ExifTagConstants.EXIF_TAG_EXIF_OFFSET, ExifTagConstants.EXIF_TAG_EXPOSURE_PROGRAM, ExifTagConstants.EXIF_TAG_SPECTRAL_SENSITIVITY, ExifTagConstants.EXIF_TAG_GPSINFO, ExifTagConstants.EXIF_TAG_ISO, ExifTagConstants.EXIF_TAG_OPTO_ELECTRIC_CONV_FACTOR, ExifTagConstants.EXIF_TAG_LEAF_SUB_IFD, ExifTagConstants.EXIF_TAG_EXIF_VERSION, ExifTagConstants.EXIF_TAG_DATE_TIME_ORIGINAL, ExifTagConstants.EXIF_TAG_DATE_TIME_DIGITIZED, ExifTagConstants.EXIF_TAG_COMPONENTS_CONFIGURATION, ExifTagConstants.EXIF_TAG_COMPRESSED_BITS_PER_PIXEL, ExifTagConstants.EXIF_TAG_SHUTTER_SPEED_VALUE, ExifTagConstants.EXIF_TAG_APERTURE_VALUE, ExifTagConstants.EXIF_TAG_BRIGHTNESS_VALUE, ExifTagConstants.EXIF_TAG_EXPOSURE_COMPENSATION, ExifTagConstants.EXIF_TAG_MAX_APERTURE_VALUE, ExifTagConstants.EXIF_TAG_SUBJECT_DISTANCE, ExifTagConstants.EXIF_TAG_METERING_MODE, ExifTagConstants.EXIF_TAG_LIGHT_SOURCE, ExifTagConstants.EXIF_TAG_FLASH, ExifTagConstants.EXIF_TAG_FOCAL_LENGTH, ExifTagConstants.EXIF_TAG_SUBJECT_AREA, ExifTagConstants.EXIF_TAG_STO_NITS, ExifTagConstants.EXIF_TAG_SUB_SEC_TIME, ExifTagConstants.EXIF_TAG_SUB_SEC_TIME_ORIGINAL, ExifTagConstants.EXIF_TAG_SUB_SEC_TIME_DIGITIZED, ExifTagConstants.EXIF_TAG_FLASHPIX_VERSION, ExifTagConstants.EXIF_TAG_EXIF_IMAGE_WIDTH, ExifTagConstants.EXIF_TAG_EXIF_IMAGE_LENGTH, ExifTagConstants.EXIF_TAG_RELATED_SOUND_FILE, ExifTagConstants.EXIF_TAG_INTEROP_OFFSET, ExifTagConstants.EXIF_TAG_FLASH_ENERGY_EXIF_IFD, ExifTagConstants.EXIF_TAG_SPATIAL_FREQUENCY_RESPONSE_2, ExifTagConstants.EXIF_TAG_NOISE_2, ExifTagConstants.EXIF_TAG_FOCAL_PLANE_XRESOLUTION_EXIF_IFD, ExifTagConstants.EXIF_TAG_FOCAL_PLANE_YRESOLUTION_EXIF_IFD, ExifTagConstants.EXIF_TAG_FOCAL_PLANE_RESOLUTION_UNIT_EXIF_IFD, ExifTagConstants.EXIF_TAG_IMAGE_NUMBER, ExifTagConstants.EXIF_TAG_SECURITY_CLASSIFICATION, ExifTagConstants.EXIF_TAG_IMAGE_HISTORY, ExifTagConstants.EXIF_TAG_SUBJECT_LOCATION, ExifTagConstants.EXIF_TAG_EXPOSURE_INDEX_EXIF_IFD, ExifTagConstants.EXIF_TAG_TIFF_EPSTANDARD_ID_2, ExifTagConstants.EXIF_TAG_SENSING_METHOD_EXIF_IFD, ExifTagConstants.EXIF_TAG_FILE_SOURCE, ExifTagConstants.EXIF_TAG_SCENE_TYPE, ExifTagConstants.EXIF_TAG_CFAPATTERN, ExifTagConstants.EXIF_TAG_CUSTOM_RENDERED, ExifTagConstants.EXIF_TAG_EXPOSURE_MODE, ExifTagConstants.EXIF_TAG_WHITE_BALANCE_1, ExifTagConstants.EXIF_TAG_DIGITAL_ZOOM_RATIO, ExifTagConstants.EXIF_TAG_FOCAL_LENGTH_IN_35MM_FORMAT, ExifTagConstants.EXIF_TAG_SCENE_CAPTURE_TYPE, ExifTagConstants.EXIF_TAG_GAIN_CONTROL, ExifTagConstants.EXIF_TAG_CONTRAST_1, ExifTagConstants.EXIF_TAG_SATURATION_1, ExifTagConstants.EXIF_TAG_SHARPNESS_1, ExifTagConstants.EXIF_TAG_DEVICE_SETTING_DESCRIPTION, ExifTagConstants.EXIF_TAG_SUBJECT_DISTANCE_RANGE, ExifTagConstants.EXIF_TAG_IMAGE_UNIQUE_ID, ExifTagConstants.EXIF_TAG_GAMMA, ExifTagConstants.EXIF_TAG_ANNOTATIONS, ExifTagConstants.EXIF_TAG_PRINT_IM, ExifTagConstants.EXIF_TAG_OFFSET_SCHEMA, ExifTagConstants.EXIF_TAG_OWNER_NAME, ExifTagConstants.EXIF_TAG_SERIAL_NUMBER, ExifTagConstants.EXIF_TAG_LENS, ExifTagConstants.EXIF_TAG_RAW_FILE, ExifTagConstants.EXIF_TAG_CONVERTER, ExifTagConstants.EXIF_TAG_WHITE_BALANCE_2, ExifTagConstants.EXIF_TAG_EXPOSURE, ExifTagConstants.EXIF_TAG_SHADOWS, ExifTagConstants.EXIF_TAG_BRIGHTNESS, ExifTagConstants.EXIF_TAG_CONTRAST_2, ExifTagConstants.EXIF_TAG_SATURATION_2, ExifTagConstants.EXIF_TAG_SHARPNESS_2, ExifTagConstants.EXIF_TAG_SMOOTHNESS, ExifTagConstants.EXIF_TAG_MOIRE_FILTER, ExifTagConstants.EXIF_TAG_USER_COMMENT, ExifTagConstants.EXIF_TAG_MAKER_NOTE));
    }
    
    private ExifTagConstants() {
    }
}
